### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by saffi-786** [SxxAq/TodoWebApp#24]
There are some issues with the Styling... In the home page the footer is invisible due to text white.. Like in the register page the navbar is repeated and the register button is also not properly structured
<img width="916" alt="Screenshot 2023-09-30 221031" src="https://github.com/SxxAq/TodoWebApp/assets/112777024/64b30434-9b43-4735-a545-fc9381d0337e">
<img width="925" alt="Screenshot 2023-09-30 220957" src="https://github.com/SxxAq/TodoWebApp/assets/112777024/0a0df6b7-0c6f-459b-8113-10e68d188809">

**Comment by saffi-786** [comment]
I would like to work on this issue under hacktoberfest... Plz assign me the issue

**Comment by saffi-786** [comment]
I have added a PR regarding issue #24 
Please review

**Comment by SxxAq** [comment]
> I have added a PR regarding issue #24 Please review

PR Merged

**Comment by saffi-786** [comment]
Thank you for merging the PR
