### ISSUE TITLE
Improve css

### ISSUE THREAD

**Issue by faizanr27** [SxxAq/TodoWebApp#5]
I want to improve the css of task container.

**Comment by Priyanshu-bit** [comment]
hi , @SxxAq I want to contribute?

**Comment by SxxAq** [comment]
> hi , @SxxAq I want to contribute?

Go through the Repo and Raise a Issue if you wanna fix or improve or add something.

**Comment by NipunKumar21** [comment]
Hi , i would like to contribute

**Comment by SxxAq** [comment]
> Hi , i would like to contribute

Go through the repo , and raise a issue.
